project_id = "bhbrkpzakzbphkytjlff"

[functions.speech-to-text]
verify_jwt = false

[functions.process-meeting]
verify_jwt = false

[functions.text-to-speech]
verify_jwt = false

[functions.twilio-voice]
verify_jwt = false

[functions.check-subscription]
verify_jwt = true

[functions.create-checkout]
verify_jwt = true

[functions.customer-portal]
verify_jwt = true