// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://bhbrkpzakzbphkytjlff.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImJoYnJrcHpha3picGhreXRqbGZmIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTE0NTk3MzIsImV4cCI6MjA2NzAzNTczMn0.HpWs2N90FHKMUfPqymCOjPnC5XdH32GdZnqtKjwY1zU";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});